---
#Main Config of VanillaEC
#Blocks can get forune
fortune.blocks:
- coal_ore
- iron_ore
- gold_ore
- diamond_ore
- leaves
- nether_quartz_ore
- glowstone
- redstone_ore
- emerald_ore
- glowing_redstone_ore

# Looting applicable entities
looting.entities:
  chicken:
  - "feather" # If drops contain feather, it'll be multiplied

...
